### ISSUE TITLE
Write the 001.run manifesto

### ISSUE THREAD

**Issue by choochootrain** [001-run/001-run.github.io#1]

**Comment by eyedoteye** [comment]
i have no idea what would be in here at all. any thoughts?

**Comment by choochootrain** [comment]
No more mediocre progress or something about the heat death of the universe
and how only glitch will remain
On Nov 27, 2015 20:58, "SideCode" notifications@github.com wrote:

i have no idea what would be in here at all. any thoughts?

**Comment by eyedoteye** [comment]
Always be dumping
No more mediocre progress
Don't plan and not do
Beware the validation trap
Enjoy the journeys
Go make cool shit
Let go of destinations
Introspection is the finest critic
Together we are stronger
Compromise arguments not artworks
Heat Death and Samsara

My shitty attempt at an acronym.

**Comment by choochootrain** [comment]
amazing
